#!/usr/bin/env bash

main() {
    temporary_credentials="$(aws \
        --profile "${AWS_PROFILE}" \
        sts assume-role \
        --role-arn="arn:aws:iam::${AWS_ACCOUNT_ID}:role/administrator" \
        --role-session-name="terraform-access"
    )"


    unset AWS_PROFILE

    export "AWS_ACCESS_KEY_ID=$(echo "${temporary_credentials}" | jq -re '.Credentials.AccessKeyId')"
    export "AWS_SECRET_ACCESS_KEY=$(echo "${temporary_credentials}" | jq -re '.Credentials.SecretAccessKey')"
    export "AWS_SESSION_TOKEN=$(echo "${temporary_credentials}" | jq -re '.Credentials.SessionToken')"

    exec terraform "$@"
}


if [ $AWS_PROFILE == "dev" ]; then
  export AWS_ACCOUNT_ID=<account id>
elif [ $AWS_PROFILE == "prod" ]; then
  export AWS_ACCOUNT_ID=<account id>
elif [ $AWS_PROFILE == "stage" ]; then
  export AWS_ACCOUNT_ID=<account id>
fi
  
    
main "$@"
